### ISSUE TITLE
linux简单安装clash

### ISSUE THREAD

**Issue by weironz** [yuanlam/Clash-Linux#4]
## linux使用clash

下载安装clash， centos8为例

```
wget https://github.com/Dreamacro/clash/releases/download/v1.6.5/clash-linux-amd64-v1.6.5.gz
gunzip -c clash-linux-amd64-v1.6.5.gz > /usr/local/bin/clash
chmod +x /usr/local/bin/clash
clash -v
```

创建clash配置文件，建议从windows客户端导出config.yaml
![clash_config.png](https://i.loli.net/2021/08/28/5ISbx2XTivEGVJg.png)

```yaml
[root@master ~]# cat /root/.config/clash/config.yaml 
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query']
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies:
    - { name: 'SG Netflix', type: ss, server: abc.01.sdfadns.tes, port: 22002, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '新加坡 02', type: ss, server: abc.01.sdfadns.tes, port: 22001, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '香港 01', type: ss, server: abc.01.sdfadns.tes, port: 22007, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '日本 01', type: ss, server: abc.01.sdfadns.tes, port: 22004, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '日本 02', type: ss, server: abc.01.sdfadns.tes, port: 22003, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '凤凰城 01', type: ss, server: abc.01.sdfadns.tes, port: 22010, cipher: chacha20-ietf-poly1305, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: 'TJ 新加坡 01', type: trojan, server: abc.01.sdfadns.tes, port: 26801, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true, skip-cert-verify: true }
proxy-groups:
    - { name: YunSails, type: select, proxies: [自动选择, 故障转移, 'SG Netflix', '新加坡 02', '香港 01', '日本 01', '日本 02', '凤凰城 01', 'TJ 新加坡 01'] }
    - { name: 自动选择, type: url-test, proxies: ['SG Netflix', '新加坡 02', '香港 01', '日本 01', '日本 02', '凤凰城 01', 'TJ 新加坡 01'], url: 'http://www.gstatic.com/generate_204', interval: 86400 }
    - { name: 故障转移, type: fallback, proxies: ['SG Netflix', '新加坡 02', '香港 01', '日本 01', '日本 02', '凤凰城 01', 'TJ 新加坡 01'], url: 'http://www.gstatic.com/generate_204', interval: 7200 }
rules:
    - 'DOMAIN,safebrowsing.urlsec.qq.com,DIRECT'
......
```

启动clash进程

```
clash
```

另起窗口，配置代理

```
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
export ALL_PROXY=socks5://127.0.0.1:7890
```

测试访问

```
curl www.google.com
```
## docker方式安装
创建clash配置文件目录
```
mkdir -p  /opt/clash/
```
创建clash配置文件

```
[root@master ~]# cat  /opt/clash/config.yaml 
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query']
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies:
    - { name: 'SG Netflix', type: ss, server: abc.01.sdfadns.tes, port: 22002, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '新加坡 02', type: ss, server: abc.01.sdfadns.tes, port: 22001, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '香港 01', type: ss, server: abc.01.sdfadns.tes, port: 22007, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '日本 01', type: ss, server: abc.01.sdfadns.tes, port: 22004, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '日本 02', type: ss, server: abc.01.sdfadns.tes, port: 22003, cipher: aes-128-gcm, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: '凤凰城 01', type: ss, server: abc.01.sdfadns.tes, port: 22010, cipher: chacha20-ietf-poly1305, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true }
    - { name: 'TJ 新加坡 01', type: trojan, server: abc.01.sdfadns.tes, port: 26801, password: ac41f43a-452e-49eb-a0ba-3e3c0e6671ed, udp: true, skip-cert-verify: true }
proxy-groups:
    - { name: YunSails, type: select, proxies: [自动选择, 故障转移, 'SG Netflix', '新加坡 02', '香港 01', '日本 01', '日本 02', '凤凰城 01', 'TJ 新加坡 01'] }
    - { name: 自动选择, type: url-test, proxies: ['SG Netflix', '新加坡 02', '香港 01', '日本 01', '日本 02', '凤凰城 01', 'TJ 新加坡 01'], url: 'http://www.gstatic.com/generate_204', interval: 86400 }
    - { name: 故障转移, type: fallback, proxies: ['SG Netflix', '新加坡 02', '香港 01', '日本 01', '日本 02', '凤凰城 01', 'TJ 新加坡 01'], url: 'http://www.gstatic.com/generate_204', interval: 7200 }
rules:
    - 'DOMAIN,safebrowsing.urlsec.qq.com,DIRECT'
......
```

启动clash
```
docker run -d --name clash-client \
  --restart always \
  -p 7890:7890 \
  -p 9090:9090 \
  -v /opt/clash/config.yaml:/root/.config/clash/config.yaml \
  dreamacro/clash
```
